### ISSUE TITLE
Query: Didn't understand how real device will run inside docker container

### ISSUE THREAD

**Issue by vikramvi** [vbanthia/appium-docker-test#1]
Thanks for this amazing project.

Can you please clarify how a real device will run inside a container ? Did you mean to say emulator / simulator inside a container ?

Also 2nd query , if I can launch emulators in parallel why I need this approach ?

May be for iOS it can hold good ?

Thanks,
Vikram

**Comment by vbanthia-zz** [comment]
I am not getting what do you mean by real device running inside container. Real Device operating system(Android) is running on its own hardware. Your machine talks with device using adb. So the only requirement to talk with android real device is to have adb client running on it.

No, I never meant emulator. Running emulator in container is possible but I never tried it by myself.

You will know how painful is it to run appium tests on multiple devices (10 ~ 15). You will have to install all the dependencies such as android, nodejs on all machines. Test environment will not be sandboxed between two devices etc etc. It is explained here in more detail, https://github.com/vbanthia/appium-docker-demo#how-to-run-above-test-without-docker

Docker approach will not work on iOS

**Comment by vikramvi** [comment]
Thanks for detailed clarifications @vbanthia

**Comment by JC0210** [comment]
Hello @vbanthia 
I have a docker container on azure cloud with appium on a ubuntu OS, and My Device is not displayed.
Steps to reproduce:
1. Run docker with " docker run -d --privileged -v /dev/bus/usb:/dev/bus/usb -p 4723:4723 -it appium/appium-docker-android bash "
2. Then i input, " docker exec "docker container number" adb devices "
3. I then get List of devices attached
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
4. Then i input, " docker exec "docker container number" adb devices "
5. I get List of devices attached but its BLANK.

What do i need to do in order for my device to be displayed when i run " docker exec "docker container number" adb devices "??? I've also tried adb connect 11.11.11.11:5555 and the request times out
Please Help
