### ISSUE TITLE
Why should I Dockerize my tests? need more info

### ISSUE THREAD

**Issue by vikramvi** [vbanthia/appium-docker-test#4]
@vbanthia can you please clarify below doubts

1. "...The only way to reduce run time is by parallelisation.." , does this mean each container run tests on individual emulator or physical device ?

2. If I've 10 android devices , how do I allocate each to individual container ?

3. I'm using Docker technology to run web automation in parallel with help of selenium grid. One container works as Hub and others are node.

4. Does this project also uses similar technique ?

Thanks in advance.

Regards,
Vikram

**Comment by argeas** [comment]
there is na issue regarding running more than 1 device. E.g. I have 2 devices and start one container. then I start another container.  running adb devices on the first container shows the devices. running adb devices on the second doesnt show anything. If I unplug and replug one device it is then seen by the second container. ( 1 on each container when running adb devices )
